token = '394461543:AAFG-QxI56h5guRboUMyrSeHXPRt551R2FA'





url_dict = {'GAZP' : 'https://www.investing.com/equities/gazprom?cid=32732',
            'LKOD' : 'https://www.investing.com/equities/nk-lukoil-oao?cid=48436', 
            'ROSN' : 'https://www.investing.com/equities/rosneft?cid=48483',
            'NVTK' : 'https://www.investing.com/equities/novatek-gdr?cid=48475',
            'SGGD' : 'https://www.investing.com/equities/surgutneftegaz?cid=48477',
            'USDRUB' : 'https://www.investing.com/currencies/usd-rub',
            'LCO' : 'https://www.investing.com/commodities/brent-oil',
            'EU50' : 'https://www.investing.com/indices/eu-stoxx50',
            'USDNOK' : 'https://www.investing.com/currencies/usd-nok',
            'EURUSD' : 'https://www.investing.com/currencies/eur-usd',
            'OBX' : 'https://www.investing.com/indices/oslo-obx',
            'BHP' : 'https://www.investing.com/equities/bhp-billiton-ltd-nyse-exch',
            'MNOD' : 'https://www.investing.com/equities/jsc-mmc-norilsk-nickel?cid=48470',
            'PL1' : 'https://www.investing.com/commodities/platinum',
            'RSX' : 'https://www.investing.com/etfs/marketvectors-tr-russia',
            'RTS' : 'https://www.investing.com/indices/rtsi',
            'CLR' : 'https://www.investing.com/equities/continental-resources-inc',
            'DVN' : 'https://www.investing.com/equities/devon-energy', 
            'MRO' : 'https://www.investing.com/equities/marathon-oil',
            'EOG' : 'https://www.investing.com/equities/eog-resources',
            'WLL' : 'https://www.investing.com/equities/whiting-petroleum-corp', 
            'SM1' : 'https://www.investing.com/indices/switzerland-20',
            'USDCHF' : 'https://www.investing.com/currencies/usd-chf',
            'CHL' : 'https://www.investing.com/equities/china-mobile-limited-exch',
            'T' : 'https://www.investing.com/equities/at-t', 
            'VOD' : 'https://www.investing.com/equities/vodafone-group-plc-exch',
            'AMX' : 'https://www.investing.com/equities/america-movil',
            'SP1' : 'https://www.investing.com/indices/us-spx-500', 
            'IYZ' : 'https://www.investing.com/etfs/ishares-djsu-telecommunications',
            'DM1' : 'https://www.investing.com/indices/us-30-futures',
            'DX1' : 'https://www.investing.com/quotes/us-dollar-index', 
            'UX1' : 'https://www.investing.com/indices/us-spx-vix-futures',
            'EWA' : 'https://www.investing.com/etfs/ishares-msci-australia-index',
            'EWC' : 'https://www.investing.com/etfs/ishares-msci-canada', 
            'AUDCAD' : 'https://www.investing.com/currencies/aud-cad',
            'USDCAD' : 'https://www.investing.com/currencies/usd-cad',
            'AUDUSD' : 'https://www.investing.com/currencies/aud-usd',
            'EZU' : 'https://www.investing.com/etfs/ishares-msci-emu', 
            'EURCAD' : 'https://www.investing.com/currencies/eur-cad',
            'EURUSD' : 'https://www.investing.com/currencies/eur-usd',
            'EWU' : 'https://www.investing.com/etfs/ishares-msci-uk',
            'EURGBP' : 'https://www.investing.com/currencies/eur-gbp',
            'GBPUSD' : 'https://www.investing.com/currencies/gbp-usd',
            'XME' : 'https://www.investing.com/etfs/spdr-s-p-metals---mining',
            'PL1' :  'https://www.investing.com/commodities/platinum',
            'HG1' : 'https://www.investing.com/commodities/copper'}

